name: Github and Slack CI CD notification

on:
  workflow_call:

jobs:
  semantic-pr:
    name: action-semantic-pull-request
    runs-on: ubuntu-latest
    uses: ./.github/workflows/semantic-pull-request.yml

  slack-workflow-status:
    if: always()
    # needs:
    #   - semantic-pr
    name: Post Workflow Status To Slack
    runs-on: ubuntu-latest
    # actions.read permission is required.
    permissions:
      actions: 'read'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#github-slack-notification-ci-cd'
          name: 'Morse Coders Workflow Bot'
          icon_emoji: ':github:'
          icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
