name: Github and Slack CI CD notification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, edited, ready_for_review, labeled, synchronize]

jobs:
  semantic-pull-requests:
    uses: ./.github/workflows/semantic-pull-request.yml
  
  # unit-tests:
  #   uses: ./.github/workflows/unit-tests.yml

  slack-workflow-status:
    needs:
    - semantic-pull-requests
    # - unit-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: Github Actions
          SLACK_CHANNEL: github-slack-notification-ci-cd
          SLACK_TITLE: Pull request success
        uses: maxwellhealth/action-slack-reporter@1.1.0

      - name: Slack Notification Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: Github Actions
          SLACK_COLOR: '#FF0000'
          SLACK_CHANNEL: github-slack-notification-ci-cd
          SLACK_TITLE: Pull request failure
        uses: maxwellhealth/action-slack-reporter@1.1.0
