name: Github and Slack CI CD notification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, edited, ready_for_review, labeled, synchronize]

jobs:
  semantic-pr:
    uses: ./.github/workflows/semantic-pull-request.yml

  slack-workflow-status:
    needs:
      - semantic-pr
    runs-on: ubuntu-latest
    steps:
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  # slack-workflow-status:
  #   if: always()
  #   needs:
  #     - semantic-pr
  #   name: Post Workflow Status To Slack
  #   runs-on: ubuntu-latest
  #   # actions.read permission is required.
  #   permissions:
  #     actions: 'read'
  #   steps:
  #     - name: Slack Workflow Notification
  #       uses: Gamesight/slack-workflow-status@master
  #       with:
  #         # Required Input
  #         repo_token: ${{secrets.GITHUB_TOKEN}}
  #         slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
  #         # Optional Input
  #         channel: '#github-slack-notification-ci-cd'
  #         name: 'Morse Coders Workflow Bot'
  #         icon_emoji: ':github:'
  #         icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
